news page API and pagination
KhashayarAsghari/olum_shenakhti pull request #2
Opened 2024-05-12 20:19 UTC by KhashayarAsghari

اتصال API صفحه اخبار و pagination

2024-05-13 18:06 UTC, mh-alahdadian requested changes

2024-05-13 18:06 UTC, mh-alahdadian commented on docs/openapi/core.json
> +    {
ایندنت اش اضافی است

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/page.tsx
> +        {news.slice(0,3).map((item: newsSingleItem) => <NewsCard {...item} />)}
این کار رو نکن که کل دیتای بکند رو اسپرید کنی تو پراپ ها بجاش 
`<NewsCard post={item} />

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/Pagination.tsx
> +interface paginationProps {
پیشنهاد میکنم از tanstack-table استفاده کنی برا مدیریت تیبل ها و پیجینیشن ها

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/Pagination.tsx
> +    const pagesCount = Math.ceil(props.itemsCount / (props.perPage ? props.perPage : 8))
use `(props.perPage || 8)` instead of `(props.perPage ? props.perPage : 8)`

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/Pagination.tsx
> +                <div onClick={()=> props.handleClick((prev: number)=> prev -1)} className="flex justify-center items-center w-[40px] h-[40px] hover:bg-gray-200">
use `button` tag

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/Pagination.tsx
> +            {(props.current > 1) &&
disable it instead of not rendering it

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/Pagination.tsx
> +                    {pagesCount >= 5 &&
از حلقه استفاده کن بجای اینکه دستی دونه به دونه بنویسی شون

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/page.tsx
> +  // ]
پاک کن کامنت ها رو

2024-05-13 18:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/page.tsx
> +  const date: string = news[0].createAt.slice(0, 10).split("-").join("/")
چرا با news[0] کار میکنی ؟ چون اولی رو میخوای متفاوت از بقیه نشون بدی ؟

بنظرم یه متغیر درست کن برای این مقدار که هر بار کروشه صفر رو ننویسی

2024-05-18 06:06 UTC, mh-alahdadian requested changes

2024-05-18 06:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/Pagination.tsx
> +            <button onClick={() => props.handleClick((prev: number) => prev - 1)} className={`${props.current === 1 ? "pointer-events-none cursor-default opacity-40" : ""} flex justify-center items-c
دو تا نکته 
* اگه جایی خواستی کلاس ها رو به هم بچسبونی از تابع clsx که نصب است استفاده کن 
* باتن یه پراپ داره به اسم disabled که اون رو ست کنی هم کلیکبل نبودنش حل میشه هم رنگش تیره میشه 
از اون استفاده کن

2024-05-18 06:06 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/page.tsx
> +        />)}
اخ نه منظورم این نبود که سینتکس اسپرید رو استفاده نکن 
منظورم این بود که کلا همه اینا رو دونه دونه نریز تو پراپ ها 

یعنی یه پراپ بده به نیوز-کارت به اسم news یا post و خود ایتم رو بهش پاس بده بره

2024-05-18 09:10 UTC, mh-alahdadian commented
من الان چک کردم یه کامپوننت پیجینیشن داریم همین الان 
```src/shared/components/Paginator.tsx```

از همین استفاده کن اگه چیزی کم داره بهترش کن

2024-06-17 10:48 UTC, KhashayarAsghari commented on src/app/(header-footer)/scope/[scopeId]/news/Pagination.tsx
> +                    {pagesCount >= 5 &&
تغییرات درخواست شده برای Pagination.tsx رو انجام ندادم که به جای این کامپوننت کلا از Paginator.tsx استفاده کنم

2024-06-22 05:17 UTC, mh-alahdadian approved these changes

2024-06-22 05:57 UTC, merged