news management
KhashayarAsghari/olum_shenakhti pull request #3
Opened 2024-06-05 18:02 UTC by KhashayarAsghari

صفحه ادمین اخبار، لطفا کد ها چک بشه که تغییرات مورد نیاز رو انجام بدم

2024-06-06 06:58 UTC, mh-alahdadian requested changes

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +import { Button } from "bootstrap";
use `<button className="btn">` instead

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +    const [pageNumber, setPageNumber] = useState(1)
use `useTable` for pagination and selection

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +    const [selectedCat, setSelectedCat] = useState<any>(null)
use category instead of cat?

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +            <table className="w-full min-w-fit">
یه کامپوننت DataTable اگه بسازی خوبه

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +                        const c = new Date(row.original.createAt!).toLocaleString('fa-IR');
use better name for your variable

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +                            <tr onClick={() => handleCatNameClick(row.original)} key={row.id} className={`${index % 2 ? "bg-gray-200" : ""} cursor-pointer`}>
use tailwind class of `even:bg-gray-200` and no js needed then

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +                                {row.getVisibleCells().map((cell: any) => (
don't overuse `any` keyword

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +                                </td> */}
چرا این کامنت شده ؟

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +                    <svg onClick={() => setIsModalVisible(false)} className="absolute cursor-pointer top-0 right-0 translate-x-1/2 -translate-y-1/2" fill="#ff0000" height="20px" width="20px" version=
what is this svg ?
just import from `@phosphor-icons/react`

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/cols.tsx
> +            return <Link className="underline text-blue-800 cursor-pointer" href={`${row.original.id}`}>{row.original.title}</Link>
use `link` or `btn-link` classNames

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/page.tsx
> +    console.log(data)
remove logs

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/page.tsx
> +                    <svg preserveAspectRatio="none" className="w-16 h-16" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
don't put svg inside code

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/page.tsx
> +                        <div className="flex gap-4 justify-center mt-3">
make a paigination component and pass `tableInstance` prop to it

2024-06-06 06:58 UTC, mh-alahdadian commented on src/app/(header-footer)/scope/[scopeId]/news/admin/page.tsx
> +                        <div className="flex gap-4 justify-center mt-3">
فکر کنم کامپوننت پیجینیشن داریم همین الان هم 
خواستی میتونی اونو بهتر کنی یا یکی دیگه بنویسی کنارش

2024-06-08 11:51 UTC, KhashayarAsghari commented on src/app/(header-footer)/scope/[scopeId]/news/admin/AdminTopicsTab.tsx
> +                                </td> */}
چون وضعیتشو از status چک میکنیم و اون همه حالتارو داره

2024-06-15 05:27 UTC, merged